-- NSQ Portal - Unified Database Setup Script

-- 0. Extensions
CREATE SCHEMA IF NOT EXISTS extensions;
-- Install extensions in a dedicated schema to keep the public API clean
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

-- 0.1 Organizations Table
CREATE TABLE IF NOT EXISTS public.organizations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    subscription_tier text DEFAULT 'free',
    credits_balance int DEFAULT 5,
    master_api_key text,
    subscription_start_date timestamptz DEFAULT now(),
    last_credit_depletion timestamptz
);

-- 1. User Profiles
CREATE TABLE public.user_profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'assessor',
  full_name text,
  org_id uuid REFERENCES public.organizations(id),
  org_role text DEFAULT 'admin',
  marketing_source text,
  primary_trade text,
  monthly_report_volume text,
  assessor_role text DEFAULT NULL  -- NSQ assessor role: QAA, IQA, or EQA
);

-- Ensure the role check constraint is up to date if the table already existed
ALTER TABLE IF EXISTS public.user_profiles 
DROP CONSTRAINT IF EXISTS user_profiles_role_check;
ALTER TABLE IF EXISTS public.user_profiles 
ADD CONSTRAINT user_profiles_role_check CHECK (role IN ('admin', 'assessor', 'student'));

-- Add assessor_role if it doesn't already exist (migration-safe)
ALTER TABLE IF EXISTS public.user_profiles
ADD COLUMN IF NOT EXISTS assessor_role text DEFAULT NULL;
ALTER TABLE IF EXISTS public.user_profiles
DROP CONSTRAINT IF EXISTS user_profiles_assessor_role_check;
ALTER TABLE IF EXISTS public.user_profiles
ADD CONSTRAINT user_profiles_assessor_role_check CHECK (assessor_role IN ('QAA', 'IQA', 'EQA') OR assessor_role IS NULL);

-- 2. NSQ Structure (NOS)
CREATE TABLE public.trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name text NOT NULL
);

CREATE TABLE public.units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    trade_id bigint REFERENCES public.trades(id) ON DELETE CASCADE, 
    code text NOT NULL, 
    title text NOT NULL
);

CREATE TABLE public.learning_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    unit_id bigint REFERENCES public.units(id) ON DELETE CASCADE, 
    lo_num text NOT NULL, 
    description text NOT NULL
);

CREATE TABLE public.performance_criteria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    lo_id bigint REFERENCES public.learning_outcomes(id) ON DELETE CASCADE, 
    pc_code text NOT NULL, 
    description text NOT NULL
);

-- 3. Assessment & Evidence Reporting
CREATE TABLE public.assessment_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name text NOT NULL CHECK (char_length(student_name) <= 150),
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    report_text text CHECK (char_length(report_text) > 0),
    assessment_date text,
    created_at timestamptz DEFAULT now(),
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

CREATE TABLE public.student_statements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    student_name text NOT NULL CHECK (char_length(student_name) <= 150),
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    reflection_notes text CHECK (char_length(reflection_notes) <= 2500),
    statement_text text CHECK (char_length(statement_text) > 0),
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

CREATE TABLE public.witness_statements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    witness_name text NOT NULL CHECK (char_length(witness_name) <= 150),
    witness_role text CHECK (char_length(witness_role) <= 150),
    candidate_name text NOT NULL CHECK (char_length(candidate_name) <= 150),
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    witness_notes text CHECK (char_length(witness_notes) <= 2500),
    statement_text text CHECK (char_length(statement_text) > 0),
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_criteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.witness_statements ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- NOS Library (Public/Authenticated Read Access)
CREATE POLICY "Allow authenticated read for trades" ON public.trades FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for units" ON public.units FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for LOs" ON public.learning_outcomes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for PCs" ON public.performance_criteria FOR SELECT TO authenticated USING (true);

-- Assessment Reports
CREATE POLICY "Creators can view their own reports" ON public.assessment_reports FOR SELECT USING (auth.uid() = created_by);
CREATE POLICY "Creators can insert their own reports" ON public.assessment_reports FOR INSERT WITH CHECK (auth.uid() = created_by);

-- Student Statements
CREATE POLICY "Individuals can create their own student statements" ON public.student_statements FOR INSERT WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Individuals can view their own student statements" ON public.student_statements FOR SELECT USING (auth.uid() = created_by);

-- Witness Statements
CREATE POLICY "Authenticated users can create witness statements" ON public.witness_statements FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Creators can view their own witness statements" ON public.witness_statements FOR SELECT USING (auth.uid() = created_by);

-- 6. Security Hardening

-- 6.1 Automation: New User Trigger Logic
-- This function runs every time a user signs up in Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user_setup()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_org_id uuid;
    org_name_val text;
BEGIN
    -- Extract the organization name from the metadata provided in auth_utils.py
    org_name_val := COALESCE(new.raw_user_meta_data->>'org_name', 'Personal Workspace');

    -- 1. Create the organization for the new user with 10 free credits
    INSERT INTO public.organizations (name, subscription_tier, credits_balance)
    VALUES (org_name_val, 'free', 5)
    RETURNING id INTO new_org_id;

    -- 2. Create the user profile linked to the new organization
    INSERT INTO public.user_profiles (
        id, 
        email, 
        full_name, 
        org_id, 
        org_role,
        marketing_source,
        primary_trade,
        monthly_report_volume
    )
    VALUES (
        new.id, 
        new.email, 
        new.raw_user_meta_data->>'full_name', 
        new_org_id, 
        'admin',
        new.raw_user_meta_data->>'marketing_source',
        new.raw_user_meta_data->>'primary_trade',
        new.raw_user_meta_data->>'monthly_volume'
    );

    RETURN new;
END;
$$;

-- Create the trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_setup();

-- Set search_path and revoke public execute for security definer functions
-- to prevent search-path hijacking and unauthorized API access.

ALTER FUNCTION public.handle_new_user_setup() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_setup() FROM PUBLIC;

ALTER FUNCTION public.rls_auto_enable() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC;

-- 6.2 Auto-Renew Free Credits Logic
-- Trigger to record when an organization's credit drops to zero
CREATE OR REPLACE FUNCTION public.handle_credit_depletion()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- If credit hits zero, record the timestamp
    IF NEW.credits_balance = 0 AND OLD.credits_balance > 0 THEN
        NEW.last_credit_depletion = now();
    -- If credit is manually topped up, clear the timestamp
    ELSIF NEW.credits_balance > 0 THEN
        NEW.last_credit_depletion = NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_credit_update ON public.organizations;
CREATE TRIGGER on_credit_update
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.handle_credit_depletion();

-- Create a daily pg_cron job to refill credits after 7 days
-- NOTE: In Supabase, you must run this specific block in the SQL Editor as a superuser.
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- SELECT cron.schedule(
--   'refill-free-credits-weekly',
--   '0 0 * * *', -- Runs every midnight
--   $$
--   UPDATE public.organizations
--   SET credits_balance = 5,
--       last_credit_depletion = NULL
--   WHERE subscription_tier = 'free'
--     AND credits_balance = 0
--     AND last_credit_depletion IS NOT NULL
--     AND last_credit_depletion <= now() - interval '7 days';
--   $$
-- );

-- ==============================================================
-- 9. Product Feedback Table
-- Stores in-app thumbs up/down ratings with optional comments.
-- ==============================================================
CREATE TABLE IF NOT EXISTS public.product_feedback (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
    assessor_role text,            -- QAA, IQA, EQA (snapshotted at time of feedback)
    rating smallint NOT NULL CHECK (rating IN (1, -1)), -- 1 = thumbs up, -1 = thumbs down
    comment text CHECK (char_length(comment) <= 500),
    source_page text NOT NULL      -- 'dashboard', 'personal_statement', 'witness_statement'
);

ALTER TABLE public.product_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert their own feedback" ON public.product_feedback FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can view all feedback" ON public.product_feedback FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_profiles WHERE id = auth.uid() AND role = 'admin')
);