-- NSQ Portal - Unified Database Setup Script

-- 0. Extensions
CREATE SCHEMA IF NOT EXISTS extensions;
-- Install extensions in a dedicated schema to keep the public API clean
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

-- 1. User Profiles
CREATE TABLE public.user_profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'assessor',
  full_name text,
  marketing_source text,
  primary_trade text,
  monthly_report_volume text
);

-- Ensure the role check constraint is up to date if the table already existed
ALTER TABLE IF EXISTS public.user_profiles 
DROP CONSTRAINT IF EXISTS user_profiles_role_check;
ALTER TABLE IF EXISTS public.user_profiles 
ADD CONSTRAINT user_profiles_role_check CHECK (role IN ('admin', 'assessor', 'student'));

-- 2. NSQ Structure (NOS)
CREATE TABLE public.trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name text NOT NULL
);

CREATE TABLE public.units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    trade_id bigint REFERENCES public.trades(id) ON DELETE CASCADE, 
    code text NOT NULL, 
    title text NOT NULL
);

CREATE TABLE public.learning_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    unit_id bigint REFERENCES public.units(id) ON DELETE CASCADE, 
    lo_num text NOT NULL, 
    description text NOT NULL
);

CREATE TABLE public.performance_criteria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    lo_id bigint REFERENCES public.learning_outcomes(id) ON DELETE CASCADE, 
    pc_code text NOT NULL, 
    description text NOT NULL
);

-- 3. Assessment & Evidence Reporting
CREATE TABLE public.assessment_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name text NOT NULL,
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    report_text text,
    assessment_date text,
    created_at timestamptz DEFAULT now(),
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

CREATE TABLE public.student_statements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    student_name text NOT NULL,
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    reflection_notes text,
    statement_text text,
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

CREATE TABLE public.witness_statements (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    witness_name text NOT NULL,
    witness_role text,
    candidate_name text NOT NULL,
    trade_id bigint REFERENCES public.trades(id) ON DELETE SET NULL,
    unit_codes text,
    witness_notes text,
    statement_text text,
    created_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_criteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.witness_statements ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- NOS Library (Public/Authenticated Read Access)
CREATE POLICY "Allow authenticated read for trades" ON public.trades FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for units" ON public.units FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for LOs" ON public.learning_outcomes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read for PCs" ON public.performance_criteria FOR SELECT TO authenticated USING (true);

-- Assessment Reports
CREATE POLICY "Creators can view their own reports" ON public.assessment_reports FOR SELECT USING (auth.uid() = created_by);
CREATE POLICY "Creators can insert their own reports" ON public.assessment_reports FOR INSERT WITH CHECK (auth.uid() = created_by);

-- Student Statements
CREATE POLICY "Individuals can create their own student statements" ON public.student_statements FOR INSERT WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Individuals can view their own student statements" ON public.student_statements FOR SELECT USING (auth.uid() = created_by);

-- Witness Statements
CREATE POLICY "Authenticated users can create witness statements" ON public.witness_statements FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Creators can view their own witness statements" ON public.witness_statements FOR SELECT USING (auth.uid() = created_by);

-- 6. Security Hardening
-- Set search_path and revoke public execute for security definer functions
-- to prevent search-path hijacking and unauthorized API access.

ALTER FUNCTION public.handle_new_user_setup() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_setup() FROM PUBLIC;

ALTER FUNCTION public.rls_auto_enable() SET search_path = public;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC;