-- 1. Create the user profiles table
CREATE TABLE public.user_profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'assessor' CHECK (role IN ('admin', 'assessor')),
  full_name text
);

-- 2. Create your NSQ tables
CREATE TABLE public.trades (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text);
CREATE TABLE public.units (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trade_id bigint REFERENCES public.trades, code text, title text);
CREATE TABLE public.learning_outcomes (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, unit_id bigint REFERENCES public.units, lo_num text, desc text);
CREATE TABLE public.performance_criteria (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lo_id bigint REFERENCES public.learning_outcomes, pc_code text, desc text);
CREATE TABLE public.assessment_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name text,
    trade_id bigint,
    unit_codes text,
    report_text text,
    assessment_date text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);