-- Level-aware NOS migration
-- Keeps legacy trade_id behavior intact while introducing trade levels as a
-- first-class concept between trades and units.

CREATE TABLE IF NOT EXISTS public.trade_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id bigint NOT NULL REFERENCES public.trades(id) ON DELETE CASCADE,
    level int NOT NULL,
    display_name text,
    source_file text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.trade_levels
    DROP CONSTRAINT IF EXISTS trade_levels_trade_id_level_key;

ALTER TABLE public.trade_levels
    ADD CONSTRAINT trade_levels_trade_id_level_key UNIQUE (trade_id, level);

ALTER TABLE public.trade_levels ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated read for trade levels" ON public.trade_levels;
CREATE POLICY "Allow authenticated read for trade levels"
ON public.trade_levels
FOR SELECT
TO authenticated
USING (true);

ALTER TABLE public.units
    ADD COLUMN IF NOT EXISTS trade_level_id bigint;

ALTER TABLE public.units
    DROP CONSTRAINT IF EXISTS units_trade_level_id_fkey;

ALTER TABLE public.units
    ADD CONSTRAINT units_trade_level_id_fkey
    FOREIGN KEY (trade_level_id)
    REFERENCES public.trade_levels(id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_trade_levels_trade_id_level ON public.trade_levels (trade_id, level);
CREATE INDEX IF NOT EXISTS idx_units_trade_level_id ON public.units (trade_level_id);
